CATEGORIES = [
    {"name": "Gaming PCs", "slug": "gaming-pcs", "icon": "Monitor", "sort_order": 1},
    {"name": "PC Components", "slug": "pc-components", "icon": "Cpu", "sort_order": 2},
    {"name": "Laptops", "slug": "laptops", "icon": "Laptop", "sort_order": 3},
    {"name": "Accessories", "slug": "accessories", "icon": "Mouse", "sort_order": 4},
    {"name": "Console Gaming", "slug": "console-gaming", "icon": "Gamepad2", "sort_order": 5},
    {"name": "Phones & Mobile", "slug": "phones-mobile", "icon": "Smartphone", "sort_order": 6},
    {"name": "Developer Zone", "slug": "developer-zone", "icon": "Code2", "sort_order": 7},
    {"name": "Creator Zone", "slug": "creator-zone", "icon": "Camera", "sort_order": 8},
    {"name": "Communities", "slug": "communities", "icon": "Users", "sort_order": 9},
    {"name": "Services", "slug": "services", "icon": "Wrench", "sort_order": 10},
]

SUBCATEGORIES = {
    "pc-components": [
        {"name": "CPUs - AMD Ryzen", "slug": "cpus-amd-ryzen", "sort_order": 1},
        {"name": "CPUs - Intel Core", "slug": "cpus-intel-core", "sort_order": 2},
        {"name": "CPUs - Server", "slug": "cpus-server", "sort_order": 3},
        {"name": "GPUs - NVIDIA RTX", "slug": "gpus-nvidia-rtx", "sort_order": 4},
        {"name": "GPUs - AMD Radeon", "slug": "gpus-amd-radeon", "sort_order": 5},
        {"name": "GPUs - Intel ARC", "slug": "gpus-intel-arc", "sort_order": 6},
        {"name": "Motherboards - Intel", "slug": "motherboards-intel", "sort_order": 7},
        {"name": "Motherboards - AMD", "slug": "motherboards-amd", "sort_order": 8},
        {"name": "Motherboards - ATX", "slug": "motherboards-atx", "sort_order": 9},
        {"name": "Motherboards - Micro ATX", "slug": "motherboards-micro-atx", "sort_order": 10},
        {"name": "Motherboards - Mini ITX", "slug": "motherboards-mini-itx", "sort_order": 11},
        {"name": "RAM - DDR4", "slug": "ram-ddr4", "sort_order": 12},
        {"name": "RAM - DDR5", "slug": "ram-ddr5", "sort_order": 13},
        {"name": "RAM - RGB", "slug": "ram-rgb", "sort_order": 14},
        {"name": "Storage - NVMe SSD", "slug": "storage-nvme-ssd", "sort_order": 15},
        {"name": "Storage - SATA SSD", "slug": "storage-sata-ssd", "sort_order": 16},
        {"name": "Storage - HDD", "slug": "storage-hdd", "sort_order": 17},
        {"name": "PSU - 550W", "slug": "psu-550w", "sort_order": 18},
        {"name": "PSU - 650W", "slug": "psu-650w", "sort_order": 19},
        {"name": "PSU - 750W", "slug": "psu-750w", "sort_order": 20},
        {"name": "PSU - 850W", "slug": "psu-850w", "sort_order": 21},
        {"name": "PSU - 1000W+", "slug": "psu-1000w", "sort_order": 22},
        {"name": "Cooling - Air", "slug": "cooling-air", "sort_order": 23},
        {"name": "Cooling - AIO Liquid", "slug": "cooling-aio", "sort_order": 24},
        {"name": "Cooling - Custom Water", "slug": "cooling-custom-water", "sort_order": 25},
        {"name": "Cases - Mid Tower", "slug": "cases-mid-tower", "sort_order": 26},
        {"name": "Cases - Full Tower", "slug": "cases-full-tower", "sort_order": 27},
        {"name": "Cases - Mini ITX", "slug": "cases-mini-itx", "sort_order": 28},
    ],
}

PRODUCTS = [
    # ===== GPUs =====
    {"name": "NVIDIA GeForce RTX 5090", "brand": "NVIDIA", "category": "GPU", "subcategory_slug": "gpus-nvidia-rtx",
     "manufacturer": "NVIDIA", "model": "RTX 5090", "price": 1999.99, "power_consumption": 575,
     "specs": {"architecture": "Blackwell", "cuda_cores": 24576, "memory": "32GB GDDR7", "memory_bus": 512, "boost_clock": "2.9 GHz"},
     "compatibility": {"pcie_version": "5.0", "required_psu": "1000W", "slot_size": "3.5 slot"}},
    {"name": "NVIDIA GeForce RTX 5080", "brand": "NVIDIA", "category": "GPU", "subcategory_slug": "gpus-nvidia-rtx",
     "manufacturer": "NVIDIA", "model": "RTX 5080", "price": 1499.99, "power_consumption": 400,
     "specs": {"architecture": "Blackwell", "cuda_cores": 18432, "memory": "24GB GDDR7", "memory_bus": 384, "boost_clock": "2.8 GHz"},
     "compatibility": {"pcie_version": "5.0", "required_psu": "850W", "slot_size": "3 slot"}},
    {"name": "NVIDIA GeForce RTX 4070", "brand": "NVIDIA", "category": "GPU", "subcategory_slug": "gpus-nvidia-rtx",
     "manufacturer": "NVIDIA", "model": "RTX 4070", "price": 549.99, "power_consumption": 200,
     "specs": {"architecture": "Ada Lovelace", "cuda_cores": 5888, "memory": "12GB GDDR6X", "memory_bus": 192, "boost_clock": "2.5 GHz"},
     "compatibility": {"pcie_version": "4.0", "required_psu": "650W", "slot_size": "2.5 slot"}},
    {"name": "AMD Radeon RX 7900 XTX", "brand": "AMD", "category": "GPU", "subcategory_slug": "gpus-amd-radeon",
     "manufacturer": "AMD", "model": "RX 7900 XTX", "price": 999.99, "power_consumption": 355,
     "specs": {"architecture": "RDNA 3", "stream_processors": 6144, "memory": "24GB GDDR6", "memory_bus": 384, "boost_clock": "2.5 GHz"},
     "compatibility": {"pcie_version": "4.0", "required_psu": "850W", "slot_size": "2.5 slot"}},
    {"name": "AMD Radeon RX 7800 XT", "brand": "AMD", "category": "GPU", "subcategory_slug": "gpus-amd-radeon",
     "manufacturer": "AMD", "model": "RX 7800 XT", "price": 499.99, "power_consumption": 263,
     "specs": {"architecture": "RDNA 3", "stream_processors": 3840, "memory": "16GB GDDR6", "memory_bus": 256, "boost_clock": "2.4 GHz"},
     "compatibility": {"pcie_version": "4.0", "required_psu": "700W", "slot_size": "2.5 slot"}},
    {"name": "Intel Arc A770", "brand": "Intel", "category": "GPU", "subcategory_slug": "gpus-intel-arc",
     "manufacturer": "Intel", "model": "Arc A770", "price": 329.99, "power_consumption": 225,
     "specs": {"architecture": "Alchemist", "xmx_cores": 512, "memory": "16GB GDDR6", "memory_bus": 256, "boost_clock": "2.1 GHz"},
     "compatibility": {"pcie_version": "4.0", "required_psu": "650W", "slot_size": "2 slot"}},
    {"name": "Intel Arc B580", "brand": "Intel", "category": "GPU", "subcategory_slug": "gpus-intel-arc",
     "manufacturer": "Intel", "model": "Arc B580", "price": 249.99, "power_consumption": 190,
     "specs": {"architecture": "Battlemage", "xmx_cores": 384, "memory": "12GB GDDR6", "memory_bus": 192, "boost_clock": "2.2 GHz"},
     "compatibility": {"pcie_version": "4.0", "required_psu": "600W", "slot_size": "2 slot"}},

    # ===== CPUs =====
    {"name": "AMD Ryzen 9 9950X", "brand": "AMD", "category": "CPU", "subcategory_slug": "cpus-amd-ryzen",
     "manufacturer": "AMD", "model": "Ryzen 9 9950X", "price": 649.99, "power_consumption": 170,
     "specs": {"architecture": "Zen 5", "cores": 16, "threads": 32, "base_clock": "4.3 GHz", "boost_clock": "5.7 GHz", "socket": "AM5", "l3_cache": "64MB", "tdp": "170W"},
     "compatibility": {"socket": "AM5", "chipset": "X670E, B650", "memory_type": "DDR5"}},
    {"name": "AMD Ryzen 7 7800X3D", "brand": "AMD", "category": "CPU", "subcategory_slug": "cpus-amd-ryzen",
     "manufacturer": "AMD", "model": "Ryzen 7 7800X3D", "price": 389.99, "power_consumption": 120,
     "specs": {"architecture": "Zen 4", "cores": 8, "threads": 16, "base_clock": "4.2 GHz", "boost_clock": "5.0 GHz", "socket": "AM5", "l3_cache": "96MB (3D V-Cache)", "tdp": "120W"},
     "compatibility": {"socket": "AM5", "chipset": "X670E, B650, A620", "memory_type": "DDR5"}},
    {"name": "AMD Ryzen 5 7600X", "brand": "AMD", "category": "CPU", "subcategory_slug": "cpus-amd-ryzen",
     "manufacturer": "AMD", "model": "Ryzen 5 7600X", "price": 219.99, "power_consumption": 105,
     "specs": {"architecture": "Zen 4", "cores": 6, "threads": 12, "base_clock": "4.7 GHz", "boost_clock": "5.3 GHz", "socket": "AM5", "l3_cache": "32MB", "tdp": "105W"},
     "compatibility": {"socket": "AM5", "chipset": "X670E, B650, A620", "memory_type": "DDR5"}},
    {"name": "AMD Ryzen 9 7950X", "brand": "AMD", "category": "CPU", "subcategory_slug": "cpus-amd-ryzen",
     "manufacturer": "AMD", "model": "Ryzen 9 7950X", "price": 549.99, "power_consumption": 170,
     "specs": {"architecture": "Zen 4", "cores": 16, "threads": 32, "base_clock": "4.5 GHz", "boost_clock": "5.7 GHz", "socket": "AM5", "l3_cache": "64MB", "tdp": "170W"},
     "compatibility": {"socket": "AM5", "chipset": "X670E, B650", "memory_type": "DDR5"}},
    {"name": "Intel Core i9-14900K", "brand": "Intel", "category": "CPU", "subcategory_slug": "cpus-intel-core",
     "manufacturer": "Intel", "model": "Core i9-14900K", "price": 589.99, "power_consumption": 253,
     "specs": {"architecture": "Raptor Lake Refresh", "cores": "24 (8P+16E)", "threads": 32, "base_clock": "3.2 GHz", "boost_clock": "6.0 GHz", "socket": "LGA1700", "l3_cache": "36MB", "tdp": "253W"},
     "compatibility": {"socket": "LGA1700", "chipset": "Z790, Z690, B760", "memory_type": "DDR5, DDR4"}},
    {"name": "Intel Core i7-14700K", "brand": "Intel", "category": "CPU", "subcategory_slug": "cpus-intel-core",
     "manufacturer": "Intel", "model": "Core i7-14700K", "price": 409.99, "power_consumption": 253,
     "specs": {"architecture": "Raptor Lake Refresh", "cores": "20 (8P+12E)", "threads": 28, "base_clock": "3.4 GHz", "boost_clock": "5.6 GHz", "socket": "LGA1700", "l3_cache": "33MB", "tdp": "253W"},
     "compatibility": {"socket": "LGA1700", "chipset": "Z790, Z690, B760", "memory_type": "DDR5, DDR4"}},
    {"name": "Intel Core i5-14600K", "brand": "Intel", "category": "CPU", "subcategory_slug": "cpus-intel-core",
     "manufacturer": "Intel", "model": "Core i5-14600K", "price": 319.99, "power_consumption": 181,
     "specs": {"architecture": "Raptor Lake Refresh", "cores": "14 (6P+8E)", "threads": 20, "base_clock": "3.5 GHz", "boost_clock": "5.3 GHz", "socket": "LGA1700", "l3_cache": "24MB", "tdp": "181W"},
     "compatibility": {"socket": "LGA1700", "chipset": "Z790, Z690, B760", "memory_type": "DDR5, DDR4"}},

    # ===== Server CPUs =====
    {"name": "AMD EPYC 9654", "brand": "AMD", "category": "CPU", "subcategory_slug": "cpus-server",
     "manufacturer": "AMD", "model": "EPYC 9654", "price": 11850.00, "power_consumption": 360,
     "specs": {"architecture": "Zen 4", "cores": 96, "threads": 192, "base_clock": "2.4 GHz", "boost_clock": "3.7 GHz", "socket": "SP5", "l3_cache": "384MB", "tdp": "360W"},
     "compatibility": {"socket": "SP5", "chipset": "AMD EPYC Platform", "memory_type": "DDR5"}},
    {"name": "Intel Xeon Platinum 8490H", "brand": "Intel", "category": "CPU", "subcategory_slug": "cpus-server",
     "manufacturer": "Intel", "model": "Xeon Platinum 8490H", "price": 17850.00, "power_consumption": 350,
     "specs": {"architecture": "Sapphire Rapids", "cores": 60, "threads": 120, "base_clock": "1.9 GHz", "boost_clock": "3.5 GHz", "socket": "LGA4677", "l3_cache": "112MB", "tdp": "350W"},
     "compatibility": {"socket": "LGA4677", "chipset": "Intel C741", "memory_type": "DDR5"}},

    # ===== RAM =====
    {"name": "Corsair Vengeance DDR5 32GB 6000MHz", "brand": "Corsair", "category": "RAM", "subcategory_slug": "ram-ddr5",
     "manufacturer": "Corsair", "model": "Vengeance DDR5", "price": 109.99, "power_consumption": 10,
     "specs": {"capacity": "32GB (2x16GB)", "type": "DDR5", "speed": "6000MHz", "cas_latency": "CL36", "voltage": "1.35V", "form_factor": "DIMM"},
     "compatibility": {"memory_type": "DDR5", "form_factor": "DIMM"}},
    {"name": "G.Skill Trident Z5 RGB 32GB DDR5 6400MHz", "brand": "G.Skill", "category": "RAM", "subcategory_slug": "ram-rgb",
     "manufacturer": "G.Skill", "model": "Trident Z5 RGB", "price": 149.99, "power_consumption": 10,
     "specs": {"capacity": "32GB (2x16GB)", "type": "DDR5", "speed": "6400MHz", "cas_latency": "CL32", "voltage": "1.35V", "form_factor": "DIMM", "rgb": True},
     "compatibility": {"memory_type": "DDR5", "form_factor": "DIMM"}},
    {"name": "G.Skill Trident Z RGB 16GB DDR4 3600MHz", "brand": "G.Skill", "category": "RAM", "subcategory_slug": "ram-rgb",
     "manufacturer": "G.Skill", "model": "Trident Z RGB", "price": 59.99, "power_consumption": 8,
     "specs": {"capacity": "16GB (2x8GB)", "type": "DDR4", "speed": "3600MHz", "cas_latency": "CL16", "voltage": "1.35V", "form_factor": "DIMM", "rgb": True},
     "compatibility": {"memory_type": "DDR4", "form_factor": "DIMM"}},
    {"name": "Corsair Vengeance LPX 16GB DDR4 3200MHz", "brand": "Corsair", "category": "RAM", "subcategory_slug": "ram-ddr4",
     "manufacturer": "Corsair", "model": "Vengeance LPX", "price": 44.99, "power_consumption": 8,
     "specs": {"capacity": "16GB (2x8GB)", "type": "DDR4", "speed": "3200MHz", "cas_latency": "CL16", "voltage": "1.35V", "form_factor": "DIMM"},
     "compatibility": {"memory_type": "DDR4", "form_factor": "DIMM"}},
    {"name": "Kingston Fury Beast DDR5 64GB 5600MHz", "brand": "Kingston", "category": "RAM", "subcategory_slug": "ram-ddr5",
     "manufacturer": "Kingston", "model": "Fury Beast DDR5", "price": 199.99, "power_consumption": 12,
     "specs": {"capacity": "64GB (2x32GB)", "type": "DDR5", "speed": "5600MHz", "cas_latency": "CL40", "voltage": "1.25V", "form_factor": "DIMM"},
     "compatibility": {"memory_type": "DDR5", "form_factor": "DIMM"}},

    # ===== Storage =====
    {"name": "Samsung 990 Pro 2TB NVMe", "brand": "Samsung", "category": "Storage", "subcategory_slug": "storage-nvme-ssd",
     "manufacturer": "Samsung", "model": "990 Pro", "price": 169.99, "power_consumption": 7.8,
     "specs": {"capacity": "2TB", "form_factor": "M.2 2280", "interface": "PCIe 4.0 x4 NVMe", "read_speed": "7450 MB/s", "write_speed": "6900 MB/s", "type": "TLC NAND"},
     "compatibility": {"interface": "M.2 PCIe 4.0", "form_factor": "M.2 2280"}},
    {"name": "WD Black SN850X 1TB NVMe", "brand": "Western Digital", "category": "Storage", "subcategory_slug": "storage-nvme-ssd",
     "manufacturer": "WD", "model": "Black SN850X", "price": 109.99, "power_consumption": 7.5,
     "specs": {"capacity": "1TB", "form_factor": "M.2 2280", "interface": "PCIe 4.0 x4 NVMe", "read_speed": "7300 MB/s", "write_speed": "6300 MB/s", "type": "TLC NAND"},
     "compatibility": {"interface": "M.2 PCIe 4.0", "form_factor": "M.2 2280"}},
    {"name": "Samsung 870 EVO 1TB SATA SSD", "brand": "Samsung", "category": "Storage", "subcategory_slug": "storage-sata-ssd",
     "manufacturer": "Samsung", "model": "870 EVO", "price": 79.99, "power_consumption": 3.5,
     "specs": {"capacity": "1TB", "form_factor": "2.5 inch", "interface": "SATA III", "read_speed": "560 MB/s", "write_speed": "530 MB/s", "type": "TLC NAND"},
     "compatibility": {"interface": "SATA III", "form_factor": "2.5 inch"}},
    {"name": "Seagate Barracuda 2TB HDD", "brand": "Seagate", "category": "Storage", "subcategory_slug": "storage-hdd",
     "manufacturer": "Seagate", "model": "Barracuda", "price": 54.99, "power_consumption": 6.5,
     "specs": {"capacity": "2TB", "form_factor": "3.5 inch", "interface": "SATA III", "rpm": "7200 RPM", "cache": "256MB"},
     "compatibility": {"interface": "SATA III", "form_factor": "3.5 inch"}},

    # ===== Motherboards =====
    {"name": "ASUS ROG Crosshair X670E Hero", "brand": "ASUS", "category": "Motherboard", "subcategory_slug": "motherboards-amd",
     "manufacturer": "ASUS", "model": "ROG Crosshair X670E Hero", "price": 499.99,
     "specs": {"form_factor": "ATX", "socket": "AM5", "chipset": "X670E", "memory_slots": 4, "max_memory": "192GB DDR5", "pcie_slots": "2x PCIe 5.0 x16", "m2_slots": 5, "wifi": "WiFi 7", "lan": "2.5Gb Ethernet"},
     "compatibility": {"socket": "AM5", "form_factor": "ATX", "memory_type": "DDR5"}},
    {"name": "MSI MAG Z790 Tomahawk WiFi", "brand": "MSI", "category": "Motherboard", "subcategory_slug": "motherboards-intel",
     "manufacturer": "MSI", "model": "MAG Z790 Tomahawk", "price": 259.99,
     "specs": {"form_factor": "ATX", "socket": "LGA1700", "chipset": "Z790", "memory_slots": 4, "max_memory": "192GB DDR5", "pcie_slots": "1x PCIe 5.0 x16, 1x PCIe 4.0 x16", "m2_slots": 4, "wifi": "WiFi 6E", "lan": "2.5Gb Ethernet"},
     "compatibility": {"socket": "LGA1700", "form_factor": "ATX", "memory_type": "DDR5, DDR4"}},
    {"name": "Gigabyte B650 AORUS Elite AX", "brand": "Gigabyte", "category": "Motherboard", "subcategory_slug": "motherboards-amd",
     "manufacturer": "Gigabyte", "model": "B650 AORUS Elite AX", "price": 199.99,
     "specs": {"form_factor": "ATX", "socket": "AM5", "chipset": "B650", "memory_slots": 4, "max_memory": "192GB DDR5", "pcie_slots": "1x PCIe 5.0 x16, 1x PCIe 4.0 x16", "m2_slots": 3, "wifi": "WiFi 6E", "lan": "2.5Gb Ethernet"},
     "compatibility": {"socket": "AM5", "form_factor": "ATX", "memory_type": "DDR5"}},
    {"name": "ASUS ROG STRIX B760-I Gaming WiFi", "brand": "ASUS", "category": "Motherboard", "subcategory_slug": "motherboards-mini-itx",
     "manufacturer": "ASUS", "model": "ROG STRIX B760-I", "price": 229.99,
     "specs": {"form_factor": "Mini ITX", "socket": "LGA1700", "chipset": "B760", "memory_slots": 2, "max_memory": "96GB DDR5", "pcie_slots": "1x PCIe 5.0 x16", "m2_slots": 2, "wifi": "WiFi 6E", "lan": "2.5Gb Ethernet"},
     "compatibility": {"socket": "LGA1700", "form_factor": "Mini ITX", "memory_type": "DDR5"}},
    {"name": "MSI MAG B760M Mortar WiFi", "brand": "MSI", "category": "Motherboard", "subcategory_slug": "motherboards-micro-atx",
     "manufacturer": "MSI", "model": "MAG B760M Mortar", "price": 179.99,
     "specs": {"form_factor": "Micro ATX", "socket": "LGA1700", "chipset": "B760", "memory_slots": 4, "max_memory": "192GB DDR5", "pcie_slots": "1x PCIe 5.0 x16", "m2_slots": 2, "wifi": "WiFi 6E", "lan": "2.5Gb Ethernet"},
     "compatibility": {"socket": "LGA1700", "form_factor": "Micro ATX", "memory_type": "DDR5"}},

    # ===== PSUs =====
    {"name": "Corsair RM550x 550W 80+ Gold", "brand": "Corsair", "category": "PSU", "subcategory_slug": "psu-550w",
     "manufacturer": "Corsair", "model": "RM550x", "price": 89.99, "power_consumption": 550,
     "specs": {"wattage": 550, "efficiency": "80+ Gold", "modular": "Full", "form_factor": "ATX", "fan": "120mm", "protection": "OCP, OVP, SCP, OTP"},
     "compatibility": {"form_factor": "ATX", "efficiency": "80+ Gold"}},
    {"name": "EVGA SuperNOVA 650 G7 650W", "brand": "EVGA", "category": "PSU", "subcategory_slug": "psu-650w",
     "manufacturer": "EVGA", "model": "SuperNOVA 650 G7", "price": 109.99, "power_consumption": 650,
     "specs": {"wattage": 650, "efficiency": "80+ Gold", "modular": "Full", "form_factor": "ATX", "fan": "135mm", "protection": "OCP, OVP, SCP, OTP, UVP"},
     "compatibility": {"form_factor": "ATX", "efficiency": "80+ Gold"}},
    {"name": "Seasonic Focus GX-750 750W", "brand": "Seasonic", "category": "PSU", "subcategory_slug": "psu-750w",
     "manufacturer": "Seasonic", "model": "Focus GX-750", "price": 99.99, "power_consumption": 750,
     "specs": {"wattage": 750, "efficiency": "80+ Gold", "modular": "Full", "form_factor": "ATX", "fan": "120mm", "protection": "OCP, OVP, SCP, OTP, UVP"},
     "compatibility": {"form_factor": "ATX", "efficiency": "80+ Gold"}},
    {"name": "Corsair RM850x 850W 80+ Gold", "brand": "Corsair", "category": "PSU", "subcategory_slug": "psu-850w",
     "manufacturer": "Corsair", "model": "RM850x", "price": 129.99, "power_consumption": 850,
     "specs": {"wattage": 850, "efficiency": "80+ Gold", "modular": "Full", "form_factor": "ATX", "fan": "135mm", "protection": "OCP, OVP, SCP, OTP"},
     "compatibility": {"form_factor": "ATX", "efficiency": "80+ Gold"}},
    {"name": "be quiet! Dark Power 13 1000W", "brand": "be quiet!", "category": "PSU", "subcategory_slug": "psu-1000w",
     "manufacturer": "be quiet!", "model": "Dark Power 13", "price": 219.99, "power_consumption": 1000,
     "specs": {"wattage": 1000, "efficiency": "80+ Titanium", "modular": "Full", "form_factor": "ATX", "fan": "135mm", "protection": "OCP, OVP, SCP, OTP, UVP"},
     "compatibility": {"form_factor": "ATX", "efficiency": "80+ Titanium"}},
    {"name": "ASUS ROG Thor 1200W Platinum II", "brand": "ASUS", "category": "PSU", "subcategory_slug": "psu-1000w",
     "manufacturer": "ASUS", "model": "ROG Thor 1200W", "price": 349.99, "power_consumption": 1200,
     "specs": {"wattage": 1200, "efficiency": "80+ Platinum", "modular": "Full", "form_factor": "ATX", "fan": "135mm RGB", "protection": "OCP, OVP, SCP, OTP, UVP"},
     "compatibility": {"form_factor": "ATX", "efficiency": "80+ Platinum"}},

    # ===== Cooling =====
    {"name": "Noctua NH-D15 Chromax Black", "brand": "Noctua", "category": "Cooling", "subcategory_slug": "cooling-air",
     "manufacturer": "Noctua", "model": "NH-D15", "price": 109.99,
     "specs": {"type": "Air Cooler", "form_factor": "Dual Tower", "fan_size": "140mm x2", "height": "165mm", "socket_support": "LGA1700, LGA1200, AM5, AM4", "tdp_rating": "250W"},
     "compatibility": {"socket": "LGA1700, AM5, AM4", "max_height": "165mm"}},
    {"name": "Cooler Master Hyper 212 Halo", "brand": "Cooler Master", "category": "Cooling", "subcategory_slug": "cooling-air",
     "manufacturer": "Cooler Master", "model": "Hyper 212 Halo", "price": 49.99,
     "specs": {"type": "Air Cooler", "form_factor": "Single Tower", "fan_size": "120mm", "height": "152mm", "socket_support": "LGA1700, LGA1200, AM5, AM4", "tdp_rating": "180W", "rgb": True},
     "compatibility": {"socket": "LGA1700, AM5, AM4", "max_height": "152mm"}},
    {"name": "Corsair H150i Elite Capellix XT 360mm AIO", "brand": "Corsair", "category": "Cooling", "subcategory_slug": "cooling-aio",
     "manufacturer": "Corsair", "model": "H150i Elite Capellix XT", "price": 179.99,
     "specs": {"type": "AIO Liquid Cooler", "radiator_size": "360mm", "fan_size": "120mm x3", "socket_support": "LGA1700, LGA1200, AM5, AM4", "rgb": True, "pump_speed": "2000 RPM"},
     "compatibility": {"socket": "LGA1700, AM5, AM4", "radiator_support": "360mm"}},
    {"name": "NZXT Kraken X73 360mm AIO", "brand": "NZXT", "category": "Cooling", "subcategory_slug": "cooling-aio",
     "manufacturer": "NZXT", "model": "Kraken X73", "price": 199.99,
     "specs": {"type": "AIO Liquid Cooler", "radiator_size": "360mm", "fan_size": "120mm x3", "socket_support": "LGA1700, LGA1200, AM5, AM4", "rgb": True, "display": "LCD Screen"},
     "compatibility": {"socket": "LGA1700, AM5, AM4", "radiator_support": "360mm"}},
    {"name": "EK-Quantum Surface P360M", "brand": "EKWB", "category": "Cooling", "subcategory_slug": "cooling-custom-water",
     "manufacturer": "EKWB", "model": "Quantum Surface P360M", "price": 129.99,
     "specs": {"type": "Custom Water Cooling Radiator", "material": "Copper/Brass", "form_factor": "360mm", "fpi": 22, "port_threads": "G1/4"},
     "compatibility": {"form_factor": "360mm", "thread": "G1/4"}},

    # ===== Cases =====
    {"name": "Corsair 4000D Airflow", "brand": "Corsair", "category": "Case", "subcategory_slug": "cases-mid-tower",
     "manufacturer": "Corsair", "model": "4000D Airflow", "price": 89.99,
     "specs": {"form_factor": "Mid Tower", "motherboard_support": "ATX, Micro ATX, Mini ITX", "psu_length_max": "220mm", "gpu_length_max": "360mm", "cooler_height_max": "170mm", "fan_slots": "6x 120mm / 4x 140mm", "drive_bays": "2x 3.5, 2x 2.5"},
     "compatibility": {"form_factor": "Mid Tower", "motherboard": "ATX, Micro ATX, Mini ITX"}},
    {"name": "NZXT H7 Flow", "brand": "NZXT", "category": "Case", "subcategory_slug": "cases-mid-tower",
     "manufacturer": "NZXT", "model": "H7 Flow", "price": 129.99,
     "specs": {"form_factor": "Mid Tower", "motherboard_support": "ATX, Micro ATX, Mini ITX", "gpu_length_max": "400mm", "cooler_height_max": "185mm", "fan_slots": "3x 120mm / 3x 140mm", "drive_bays": "2x 3.5, 2x 2.5"},
     "compatibility": {"form_factor": "Mid Tower", "motherboard": "ATX, Micro ATX, Mini ITX"}},
    {"name": "Lian Li O11 Dynamic EVO", "brand": "Lian Li", "category": "Case", "subcategory_slug": "cases-mid-tower",
     "manufacturer": "Lian Li", "model": "O11 Dynamic EVO", "price": 149.99,
     "specs": {"form_factor": "Mid Tower", "motherboard_support": "ATX, Micro ATX, Mini ITX", "gpu_length_max": "420mm", "cooler_height_max": "155mm", "fan_slots": "10x 120mm / 4x 140mm", "drive_bays": "2x 3.5, 3x 2.5"},
     "compatibility": {"form_factor": "Mid Tower", "motherboard": "ATX, Micro ATX, Mini ITX"}},
    {"name": "Fractal Design Meshify 2 XL", "brand": "Fractal Design", "category": "Case", "subcategory_slug": "cases-full-tower",
     "manufacturer": "Fractal Design", "model": "Meshify 2 XL", "price": 199.99,
     "specs": {"form_factor": "Full Tower", "motherboard_support": "E-ATX, ATX, Micro ATX, Mini ITX", "gpu_length_max": "470mm", "cooler_height_max": "185mm", "fan_slots": "11x 120mm / 8x 140mm", "drive_bays": "6x 3.5, 4x 2.5"},
     "compatibility": {"form_factor": "Full Tower", "motherboard": "E-ATX, ATX, Micro ATX, Mini ITX"}},
    {"name": "Cooler Master MasterBox NR200P", "brand": "Cooler Master", "category": "Case", "subcategory_slug": "cases-mini-itx",
     "manufacturer": "Cooler Master", "model": "MasterBox NR200P", "price": 99.99,
     "specs": {"form_factor": "Mini ITX", "motherboard_support": "Mini ITX", "gpu_length_max": "330mm", "cooler_height_max": "155mm", "fan_slots": "5x 120mm", "drive_bays": "2x 3.5, 2x 2.5"},
     "compatibility": {"form_factor": "Mini ITX", "motherboard": "Mini ITX"}},
    {"name": "Fractal Design Terra", "brand": "Fractal Design", "category": "Case", "subcategory_slug": "cases-mini-itx",
     "manufacturer": "Fractal Design", "model": "Terra", "price": 179.99,
     "specs": {"form_factor": "Mini ITX", "motherboard_support": "Mini ITX", "gpu_length_max": "322mm", "cooler_height_max": "77mm", "fan_slots": "2x 120mm", "material": "Anodized Aluminum + Walnut"},
     "compatibility": {"form_factor": "Mini ITX", "motherboard": "Mini ITX"}},
]
